Slackbot CI integration for posting CI results
Signed-off-by: Jeremy Berchtold <jberchtold@nvidia.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -51,6 +51,9 @@ variables:
       value: 0
     TAG_ROOT:
       description: Base for container tags (<TAG_ROOT>-<FRAMEWORK>-py3-<BUILD_STAGE>)
+    SEND_SLACK_MESSAGE:
+      description: Send Slack message when the CI pipeline completes
+      value: 1
 
     VIRTUAL: 0
     JOB_START_STRING: "=== JOB START ==="
@@ -583,6 +586,30 @@ upload_logs:
           test $CURL_RESULT && exit 0
       done
     - exit 1
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "pipeline" && $CI_COMMIT_BRANCH =~ /^pr_/
+      when: always
+  tags:
+    - vm-builder
+
+send_result_to_slack:
+  stage: finalize
+  script:
+    - echo "${gitHubData}"
+    - |
+      function sendSlackMessage() {
+        if [[ "${SEND_SLACK_MESSAGE}" == "1" ]]; then
+          SLACK_MESSAGE_MRKDWN=${1}
+          PARENT_MESSAGE_TS=${2}
+          jq '{channel: $channel, blocks: []}' -n --arg channel "#swdl-fw-model-perf-ci" > payload.json 
+          [ -n "${SLACK_MESSAGE_MRKDWN}" ] && jq_in_place '.blocks += [{type: "section", text: {type: "mrkdwn", text: $mrkdwn}}]' payload.json --arg mrkdwn "${SLACK_MESSAGE_MRKDWN}"
+          [ -n "$PARENT_MESSAGE_TS" ] && jq_in_place '. += {"thread_ts" : $ts}' payload.json --arg ts ${PARENT_MESSAGE_TS//\"/}
+          curl -X POST https://slack.com/api/chat.postMessage -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" -H "Content-Type: application/json" -d @payload.json -o response.json || (echo "Curl command failed with status $?"; exit 1)
+          cat response.json | jq '.' > /dev/null
+          (jq -e '.ok == true' response.json > /dev/null && echo $(jq -e '.ts' response.json)) || (echo "Slack API request failed"; exit 1)
+        fi
+      }
+    - sendSlackMessage "CI Pipeline [${CI_PIPELINE_ID}](https://gitlab-master.nvidia.com/dl/transformerengine/transformerengine/-/pipelines/${CI_PIPELINE_ID}) completed"
   rules:
     - if: $CI_PIPELINE_SOURCE == "pipeline" && $CI_COMMIT_BRANCH =~ /^pr_/
       when: always
